<?php

use Drupal\decreto_pdf2htmlex\Utils\DecretoPdf2htmlexUtils as DecretoHTMLUtils;
use Drupal\file\Entity\File;

/**
 * Implements hook_theme().
 */
function decreto_pdf2htmlex_theme() {
  return array(
    'decreto_pdf2htmlex_rendered_html_formatter' => array(
      'variables' => array('file' => NULL),
    ),
    'decreto_pdf2htmlex_rendered_html_first_page_formatter' => array(
      'variables' => array('file' => NULL),
    ),
  );
}

/**
 * Implements template_preprocess_decreto_pdf2htmlex_rendered_html_formatter().
 */
function template_preprocess_decreto_pdf2htmlex_rendered_html_formatter(&$vars) {
  template_preprocess_file_link($vars);
  $vars['html'] = DecretoHTMLUtils::getAllPages($vars['file']);
}

/**
 * Implements template_preprocess_decreto_pdf2htmlex_rendered_html_first_page_formatter().
 */
function template_preprocess_decreto_pdf2htmlex_rendered_html_first_page_formatter(&$vars) {
  template_preprocess_file_link($vars);
  $vars['html'] = DecretoHTMLUtils::getFirstPage($vars['file']);
}

/**
 * Implements hook_cron()
 */
function decreto_pdf2htmlex_cron() {
  //TODO: is that needed?
  // Clean up pdf2htmlEX garbage before converting
  //shell_exec('find /tmp/pdf2htmlEX-* -mtime +1 -delete 2> /dev/null');

  $queue_factory = \Drupal::service('queue');
  $queue = $queue_factory->get('decreto_pdf2htmlex_queue');

  $scheduled_files = DecretoHTMLUtils::getScheduledFiles();

  foreach ($scheduled_files as $schedule_file) {
    $queue->createItem($schedule_file);
  }
}

/**
 * Implement hook_entity_delete()
 *
 * @param File $file
 */
function decreto_pdf2htmlex_file_delete(File $file) {
  if (DecretoHTMLUtils::isScheduled($file)) {
    DecretoPDFUtils::deleteScheduledJob($file->id());
  }
}