<?php

/**
 * @file
 * Contains decreto_user.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function decreto_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the decreto_user module.
    case 'help.page.decreto_user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Decreto users functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_decreto_help_messages().
 */
function decreto_user_decreto_help_messages() {
  return [
    'user_search_popup' => 'User search popup',
    'user_view_page' => 'User view page',
    'user_create_edit_form' => 'User create/edit form',
  ];
}

/**
 * Implements hook_user_format_name_alter().
 *
 * If user has both first and last names, they are used as the user display
 * name.
 */
function decreto_user_user_format_name_alter(&$name, $account) {
  if ($account instanceof UserInterface == FALSE) {
    $user = User::load($account->id());
  }
  else {
    $user = $account;
  }

  if ($user) {
    $firstName = '';
    $lastName = '';

    // Getting first name.
    if ($user->field_decreto_firstname && !$user->field_decreto_firstname->isEmpty()) {
      if ($field_firstname = $user->get('field_decreto_firstname')->getValue()) {
        $firstName = $field_firstname[0]['value'];
      }
    }
    // Getting last name.
    if ($user->get('field_decreto_lastname') && !$user->field_decreto_lastname->isEmpty()) {
      if ($field_lastname = $user->get('field_decreto_lastname')->getValue()) {
        $lastName = $field_lastname[0]['value'];
      }
    }

    // Only making swap if both first and last names are present.
    if ($firstName && $lastName) {
      $name = $firstName . ' ' . $lastName;
    }
  }
}

/**
 * Implements hook_theme().
 */
function decreto_user_theme() {
  return [
    'decreto_user_users_view_context_links' => [
      'variables' => [
        'create_user' => NULL,
        'create_user_use_ajax' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function decreto_user_views_data() {
  $data['views']['decreto_user_users_view_context_links'] = [
    'title' => t('Decreto user view links'),
    'help' => t('Renders "Create" link to be used in department views.'),
    'area' => [
      'id' => 'decreto_user_users_view_context_links',
    ],
  ];

  return $data;
}
