<?php

use Drupal\decreto_content_modify\Entity\DecretoBulletPoint;
use Drupal\decreto_content_modify\Entity\DecretoBulletPointAttachment;
use Drupal\decreto_content_modify\Entity\DecretoMeeting;
use Drupal\decreto_content_modify\Entity\DecretoMemo;
use Drupal\decreto_content_modify\Form\SearchInMeetingForm;
use Drupal\decreto_content_modify\Services\ContentService;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_preprocess_node().
 */
function decreto_content_modify_preprocess_node(&$variables) {
  $node = $variables['node'];
  $view_mode = $variables['elements']['#view_mode'];

  // Adding search in meeting form.
  if ($node->getType() == 'decreto_meeting') {
    if ($view_mode == 'full') {
      $variables['search_in_meeting_form'] = \Drupal::formBuilder()->getForm(SearchInMeetingForm::class, $node);
    }
  }

  // Adding node id as data element.
  if ($node->getType() == 'decreto_bullet_point' || $node->getType() == 'decreto_bullet_point_attachment') {
    if ($view_mode == 'teaser') {
      $variables['attributes']['data-decreto-node-id'] = $node->id();
    }
  }
}

/*
 * Implements hook_search_api_solr_documents_alter().
 *
 * Adds meeting_nid field to bp and bpa nodes.
 */
function decreto_content_modify_search_api_solr_documents_alter(array &$documents, \Drupal\search_api\IndexInterface $index, array $items) {
  if ($index->id() == 'decreto_meeting_contents_index') {
    foreach ($documents as $document) {
      $item_id = $document->getFields()['ss_search_api_id'];
      $item = $items[$item_id];
      $originalEntity = $item->getOriginalObject()->getEntity();

      $meeting_nid = 0;

      if ($originalEntity->getType() == 'decreto_bullet_point') {
        $decretoBP = new DecretoBulletPoint($originalEntity);
        $meeting_nid = $decretoBP->getMeeting(FALSE);
      }
      elseif ($originalEntity->getType() == 'decreto_bullet_point_attachment') {
        $decretoBPA = new DecretoBulletPointAttachment($originalEntity);
        $meeting_nid = $decretoBPA->getMeeting(FALSE);
      }

      $document->setField('itm_meeting_nid', $meeting_nid);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Invalidates caches related with the decreto_memo and decreto_meeting.
 */
function decreto_content_modify_node_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'decreto_memo') {
    // Invalidating memos count.
    Cache::invalidateTags([ContentService::CACHE_ID_DECRETO_MEMO_COUNTERS . ':' . $entity->getOwnerId()]);

    // Getting related meeting.
    $decretoMemo = new DecretoMemo($entity);
    $meeting = $decretoMemo->getMeeting();

    // Invalidating meeting.
    if ($meeting) {
      Cache::invalidateTags($meeting->getCacheTagsToInvalidate());
    }
  }
  elseif ($entity->bundle() == 'decreto_meeting') {
    // Invalidating meetings count.
    Cache::invalidateTags([ContentService::CACHE_ID_DECRETO_MEETING_COUNTERS]);


  }
  elseif ($entity->bundle() == 'decreto_bullet_point') {
  }
  elseif ($entity->bundle() == 'decreto_bullet_point_attachment') {
    // Duplicating file reference to the related meeting as well.
    $decretoBPA = new DecretoBulletPointAttachment($entity);

    $old_related_fid = NULL;
    if ($entity->original) {
      $originalDecretoBPA = new DecretoBulletPointAttachment($entity->original);
      $old_related_fid = $originalDecretoBPA->getFile(FALSE);
    }
    $new_related_fid = $decretoBPA->getFile(FALSE);

    $meeting = $decretoBPA->getMeeting();
    if ($meeting) {
      $decretoMeeting = new DecretoMeeting($meeting);

      // Remove file from meeting.
      if ($old_related_fid && $old_related_fid != $new_related_fid) {
        $decretoMeeting->removeBpaFile($old_related_fid);
      }

      // Add file to meeting, if it's not present there yet.
      if ($new_related_fid) {
        $decretoMeeting->addBpaFile($new_related_fid);
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function decreto_content_modify_node_predelete(EntityInterface $entity) {
  if ($entity->bundle() == 'decreto_bullet_point') {
    // Deleting related memos.
    $decretoBP = new DecretoBulletPoint($entity);
    $memos = $decretoBP->getMemos();
    if (!empty($memos)) {
      foreach ($memos as $memo) {
        $memo->delete();
      }
    }

    // Deleting related BPA.
    $bpas = $decretoBP->getBulletPointAttachments();
    if (!empty($bpas)) {
      foreach ($bpas as $bpa) {
        $bpa->delete();
      }
    }
  }
  elseif ($entity->bundle() == 'decreto_bullet_point_attachment') {
    // Deleting related notes.
    $decretoBPA = new DecretoBulletPointAttachment($entity);
    $notes = $decretoBPA->getNotes();

    if (!empty($notes)) {
      foreach ($notes as $note) {
        $note->delete();
      }
    }

    // Removing BPA file from meeting.
    $fid = $decretoBPA->getFile(FALSE);
    $meeting = $decretoBPA->getMeeting();
    if ($meeting && $fid) {
      $decretoMeeting = new DecretoMeeting($meeting);
      $decretoMeeting->removeBpaFile($fid);
    }
  }
}
/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Invalidates caches related with the decreto_memo and decreto_meeting.
 */
function decreto_content_modify_node_delete(EntityInterface $entity) {
  if ($entity->bundle() == 'decreto_memo') {
    // Invalidating memos count.
    Cache::invalidateTags([ContentService::CACHE_ID_DECRETO_MEMO_COUNTERS . ':' . $entity->getOwnerId()]);

    // Getting related meeting.
    $decretoMemo = new DecretoMemo($entity);
    $meeting = $decretoMemo->getMeeting();

    // Invalidating meeting.
    if ($meeting) {
      Cache::invalidateTags($meeting->getCacheTagsToInvalidate());
    }
  }
  elseif ($entity->bundle() == 'decreto_meeting') {
    // Invalidating meetings count.
    Cache::invalidateTags([ContentService::CACHE_ID_DECRETO_MEETING_COUNTERS]);

    // Deleting related BP.
    $decretoMeeting = new DecretoMeeting($entity);
    $bps = $decretoMeeting->getBulletPoints();
    if (!empty($bps)) {
      foreach ($bps as $bp) {
        $bp->delete();
      }
    }

    // Deleting related messages (deleting message will also delete related
    // notifications).
    $messages = $decretoMeeting->getMessages();
    if (!empty($messages)) {
      foreach ($messages as $message) {
        $message->delete();
      }
    }
  }
  elseif ($entity->bundle() == 'decreto_bullet_point') {
    // Deleting this BP from meeting.
    $decretoBP = new DecretoBulletPoint($entity);
    $meeting = $decretoBP->getMeeting();
    if ($meeting) {
      $decretoMeeting = new DecretoMeeting($meeting);
      $decretoMeeting->removeBulletPoint($entity->id());
    }
  }
  elseif ($entity->bundle() == 'decreto_bullet_point_attachment') {
    // Deleting this BPA from BP.
    $decretoBPA = new DecretoBulletPointAttachment($entity);
    $bp = $decretoBPA->getBulletPoint();
    if ($bp) {
      $decretoBP = new DecretoBulletPoint($bp);
      $decretoBP->removeBulletPointAttachment($entity->id());
    }
  }

}

/**
 * Implements hook_decreto_help_messages().
 */
function decreto_content_modify_decreto_help_messages() {
  return [
    'meetings_create_edit_form' => 'Meeting create/edit form',
    'meetings_search_in_meeting_form' => 'Search in meeting form',
    'bpa_edit_form' => 'Bullet point attachment edit form',
    'memos_add_edit_form' => 'Memos create/edit form',
    'memos_read_popup' => 'Bullet point memos read popup',
  ];
}

function decreto_content_modify_theme() {
  return [
    'decreto_content_modify_bpa_edit_form' => [
      'render element' => 'form',
    ],
  ];
}
