<?php

use LasseRafn\Initials\Initials;

/**
 * Implements hook_preprocess_html().
 */
function custom_theme_preprocess_html(array &$variables) {}

/**
 * Implements hook_preprocess_page().
 */
function custom_theme_preprocess_page(array &$variables) {

  // Notification counter.
  $notificationService = \Drupal::service('decreto_notification.notification');
  $notificationCounter = $notificationService->getCounters();
  $variables['counter']['notification'] = $notificationCounter['total'];

  // Note counter.
  $noteService = \Drupal::service('decreto_annotator.note');
  $noteCounter = $noteService->getCounters();
  $variables['counter']['note'] = $noteCounter['total'];

  // Memo counter.
  $contentService = \Drupal::service('decreto_content_modify.content');
  $memoCounter = $contentService->getMemoCounters();
  $variables['counter']['memo'] = $memoCounter['total'];

  // Get initials of user.
  $account = \Drupal::currentUser();
  $user = \Drupal\user\Entity\User::load($account->id());

  $name = '';
  $firstname = '';
  $lastname = '';
  if ($user->field_decreto_firstname && !$user->field_decreto_firstname->isEmpty()) {

    if ($field_firstname = $user->get('field_decreto_firstname')->getValue()) {
      $firstname = $field_firstname[0]['value'];
    }
  }
  if ($user->field_decreto_lastname && !$user->field_decreto_lastname->isEmpty()) {

    if ($field_lastname = $user->get('field_decreto_lastname')->getValue()) {
      $lastname = $field_lastname[0]['value'];
    }
  }
  if ($firstname && $lastname) {
    $name = $firstname . ' ' . $lastname;
  } else {
    $name = $user->getDisplayName();
  }

  $variables['user_name'] = $name;
  $variables['user_initials'] = (new Initials())->name($name)->generate();
}

/*
 * Implements hook_preprocess_paragraph().
 */
function custom_theme_preprocess_paragraph(&$variables) {}


/**
 * Implements template_preprocess_taxonomy_term().
 */
function custom_theme_preprocess_taxonomy_term(&$variables) {
  $term = $variables['term'];
  $view_mode = $variables['view_mode'];

  // Initials of name.
  $name = $term->getName();
  $variables['name_raw'] = $name;
  $variables['name_initials'] = (new Initials())->name($name)->generate();
}

/*
 * Implements hook_theme_suggestions_taxonomy_term_alter().
 */
function custom_theme_theme_suggestions_taxonomy_term_alter(
  &$suggestions,
  $variables,
  $hook
) {
  $suggestions[] = 'taxonomy_term__' . $variables['elements']['#taxonomy_term']->getVocabularyId() . '__' . $variables['elements']['#view_mode'];
  $suggestions[] = 'taxonomy_term__' . $variables['elements']['#view_mode'];
}

/**
 * Implement hook_preprocess_block()
 */
function custom_theme_preprocess_block(&$variables) {
  $id = $variables['elements']['#id'];
  $variables['content']['#attributes']['block'] = $id;

  if ($id === 'custom_theme_decreto_dashboard_counter_coming_meetings') {
    $contentService = \Drupal::service('decreto_content_modify.content');
    $meetingCounter = $contentService->getMeetingCounters();

    $variables['content']['#current_organization'] = $meetingCounter['my_org'];
    $variables['content']['#across_organizations'] = $meetingCounter['total'];

    // Disable caching on block level, as we already cache the counters.
    $variables['#cache']['max-age'] = 0;
  }
  elseif ($id === 'custom_theme_decreto_dashboard_counter_departments') {
    $contentService = \Drupal::service('decreto_content_modify.content');
    $taxonomyCounter = $contentService->getDepartmentCounters();

    $variables['content']['#current_organization'] = $taxonomyCounter['my_org'];
    $variables['content']['#across_organizations'] = $taxonomyCounter['total'];

    // Disable caching on block level, as we already cache the counters.
    $variables['#cache']['max-age'] = 0;
  }
  elseif ($id === 'custom_theme_decreto_dashboard_counter_memos') {
    $contentService = \Drupal::service('decreto_content_modify.content');
    $memoCounter = $contentService->getMemoCounters();

    $variables['content']['#current_organization'] = $memoCounter['my_org'];
    $variables['content']['#across_organizations'] = $memoCounter['total'];

    // Disable caching on block level, as we already cache the counters.
    $variables['#cache']['max-age'] = 0;
  }
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node(&$variables) {
  $node = $variables['node'];
  $user = $node->getOwner();

  // Get initials of user.
  $name = '';
  $firstname = '';
  $lastname = '';
  if ($user->field_decreto_firstname && !$user->field_decreto_firstname->isEmpty()) {

    if ($field_firstname = $user->get('field_decreto_firstname')->getValue()) {
      $firstname = $field_firstname[0]['value'];
    }
  }
  if ($user->field_decreto_lastname && !$user->field_decreto_lastname->isEmpty()) {

    if ($field_lastname = $user->get('field_decreto_lastname')->getValue()) {
      $lastname = $field_lastname[0]['value'];
    }
  }
  if ($firstname && $lastname) {
    $name = $firstname . ' ' . $lastname;
  } else {
    $name = $user->getDisplayName();
  }

  $variables['user_name'] = $name;
  $variables['user_initials'] = (new Initials())->name($name)->generate();

  // Initials of title.
  $title = $node->getTitle();
  $variables['label_raw'] = $title;
  $variables['label_initials'] = (new Initials())->name($title)->generate();
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node__decreto_meeting(&$variables) {
  $node = $variables['node'];

  if ($variables['view_mode'] == 'table_display') {
    // Note indicator.
    $noteService = \Drupal::service('decreto_annotator.note');
    $variables['content']['contains_notes'] = $noteService->getMeetingHasNote($node);

    // Memos indicator.
    $decretoContentService = \Drupal::service('decreto_content_modify.content');
    $variables['content']['contains_memos'] = $decretoContentService->getMeetingHasMemo($node);
  }
}
