<?php

use Drupal\Core\Url;
use Drupal\decreto_content_modify\Controller\AccessController;
use Drupal\decreto_content_modify\Entity\DecretoBulletPoint;
use Drupal\decreto_content_modify\Entity\DecretoBulletPointAttachment;
use Drupal\decreto_content_modify\Entity\DecretoMeeting;
use Drupal\decreto_content_modify\Entity\DecretoMemo;
use Drupal\decreto_content_modify\Services\ContentService;
use Drupal\decreto_department\Services\DepartmentService;
use Drupal\user\Entity\User;
use LasseRafn\Initials\Initials;

/**
 * Implements hook_preprocess_html().
 */
function custom_theme_preprocess_html(array &$variables) {}

/**
 * Implements hook_preprocess_page().
 */
function custom_theme_preprocess_page(array &$variables) {

  // Notification counter.
  $notificationService = \Drupal::service('decreto_notification.notification');
  $notificationCounter = $notificationService->getCounters();
  $variables['counter']['notification'] = $notificationCounter['my_org'];

  // Note counter.
  $noteService = \Drupal::service('decreto_annotator.note');
  $noteCounter = $noteService->getCounters();
  $variables['counter']['note'] = $noteCounter['my_org'];

  // Memo counter.
  $contentService = \Drupal::service('decreto_content_modify.content');
  $memoCounter = $contentService->getMemoCounters();
  $variables['counter']['memo'] = $memoCounter['my_org'];

  // Access params.
  $variables['content']['#access']['decreto_meeting']['canCreate'] = AccessController::createMeetingAccess()->isAllowed();

  // Get initials of user.
  $account = \Drupal::currentUser();
  $user = User::load($account->id());

  $name = '';
  $firstname = '';
  $lastname = '';
  if ($user->field_decreto_firstname && !$user->field_decreto_firstname->isEmpty()) {

    if ($field_firstname = $user->get('field_decreto_firstname')->getValue()) {
      $firstname = $field_firstname[0]['value'];
    }
  }
  if ($user->field_decreto_lastname && !$user->field_decreto_lastname->isEmpty()) {

    if ($field_lastname = $user->get('field_decreto_lastname')->getValue()) {
      $lastname = $field_lastname[0]['value'];
    }
  }
  if ($firstname && $lastname) {
    $name = $firstname . ' ' . $lastname;
  }
  else {
    $name = $user->getDisplayName();
  }

  $variables['user_name'] = $name;
  $variables['user_initials'] = (new Initials())->name($name)->generate();

  // Getting user selected organisation.
  $organisation = \Drupal::service('decreto_organisation.organisation')->getSelectedOrganisation();
  if ($organisation) {
    $variables['selected_organisation_name'] = $organisation->label();
  }
}

/*
 * Implements hook_preprocess_paragraph().
 */
function custom_theme_preprocess_paragraph(&$variables) {}


/**
 * Implements template_preprocess_taxonomy_term().
 */
function custom_theme_preprocess_taxonomy_term(&$variables) {
  $term = $variables['term'];
  $view_mode = $variables['view_mode'];

  // Initials of name.
  $name = $term->getName();
  $variables['name_raw'] = $name;
  $variables['name_initials'] = (new Initials())->name($name)->generate();

  // Term bundle specific variables.
  if ($term->bundle() == 'decreto_tax_department') {
    if ($view_mode == 'full') {
      $variables['help_message'] = \Drupal::service('decreto_help.message')->getMessageMarkup('department_view_page');
    }
  }
}

/*
 * Implements hook_theme_suggestions_taxonomy_term_alter().
 */
function custom_theme_theme_suggestions_taxonomy_term_alter(
  &$suggestions,
  $variables,
  $hook
) {
  $suggestions[] = 'taxonomy_term__' . $variables['elements']['#taxonomy_term']->getVocabularyId() . '__' . $variables['elements']['#view_mode'];
  $suggestions[] = 'taxonomy_term__' . $variables['elements']['#view_mode'];
}

/**
 * Implement hook_preprocess_block()
 */
function custom_theme_preprocess_block(&$variables) {
  $id = $variables['elements']['#id'];
  $variables['content']['#attributes']['block'] = $id;

  if ($id === 'custom_theme_decreto_dashboard_counter_coming_meetings') {
    $contentService = \Drupal::service('decreto_content_modify.content');
    $meetingCounter = $contentService->getMeetingCounters();

    $variables['content']['#current_organisation'] = $meetingCounter['my_org'];
    $variables['content']['#other_organisations'] = $meetingCounter['total'] - $meetingCounter['my_org'];

    $current_org_popup_url = Url::fromRoute('view.decreto_meetings.decreto_page_meetings');
    $variables['content']['#current_organisation_popup_path'] = $current_org_popup_url->toString();

    $other_org_popup_url = Url::fromRoute('view.decreto_meetings.decreto_page_other_organisations_meetings');
    $variables['content']['#other_organisations_popup_path'] = $other_org_popup_url->toString();

    // Disable caching on block level, as we already cache the counters.
    $variables['#cache']['max-age'] = 0;

    // Making block aware of the counter tags.
    $variables['#cache']['tags'][] = ContentService::CACHE_ID_DECRETO_MEETING_COUNTERS;
  }
  elseif ($id === 'custom_theme_decreto_dashboard_counter_departments') {
    $departmentService = \Drupal::service('decreto_department.department');
    $departmentCounter = $departmentService->getCounters();

    $variables['content']['#current_organisation'] = $departmentCounter['my_org'];
    $variables['content']['#other_organisations'] = $departmentCounter['total'] - $departmentCounter['my_org'];

    $current_org_popup_url = Url::fromRoute('view.decreto_departments.decreto_page_departments');
    $variables['content']['#current_organisation_popup_path'] = $current_org_popup_url->toString();

    $other_org_popup_url = Url::fromRoute('view.decreto_departments.decreto_page_other_organisations_departments');
    $variables['content']['#other_organisations_popup_path'] = $other_org_popup_url->toString();

    // Making block aware of the counter tags.
    $variables['#cache']['tags'][] = DepartmentService::CACHE_ID_DECRETO_DEPARTMENT_COUNTERS;
  }
  elseif ($id === 'custom_theme_decreto_dashboard_counter_memos') {
    $contentService = \Drupal::service('decreto_content_modify.content');
    $memoCounter = $contentService->getMemoCounters();

    $variables['content']['#current_organisation'] = $memoCounter['my_org'];
    $variables['content']['#other_organisations'] = $memoCounter['total'] - $memoCounter['my_org'];

    $current_org_popup_url = Url::fromRoute('view.decreto_memos.decreto_page_memos');
    $variables['content']['#current_organisation_popup_path'] = $current_org_popup_url->toString();

    $other_org_popup_url = Url::fromRoute('view.decreto_memos.decreto_page_other_organisations_memos');
    $variables['content']['#other_organisations_popup_path'] = $other_org_popup_url->toString();

    // Making block aware of the counter tags.
    $variables['#cache']['tags'][] = ContentService::CACHE_ID_DECRETO_MEMO_COUNTERS;
  }
  elseif ($id === 'custom_theme_views_block__decreto_meetings_decreto_block_all_meetings') {
    $variables['#cache']['tags'][] = 'user:' . \Drupal::currentUser()->id();
  }
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node(&$variables) {
  $node = $variables['node'];
  $view_mode = $variables['view_mode'];
  $user = $node->getOwner();

  // Date.
  $createdAt = $node->getCreatedTime();
  if (time() - $createdAt < 24*60*60) { // today.
    $variables['date'] = \Drupal::service('date.formatter')->format($createdAt, 'html_time', '');
  }
  else { // not today.
    $variables['date'] = \Drupal::service('date.formatter')->format($createdAt, 'html_date', '');
  }

  // Get initials of user.
  $name = '';
  $firstname = '';
  $lastname = '';
  if ($user->field_decreto_firstname && !$user->field_decreto_firstname->isEmpty()) {

    if ($field_firstname = $user->get('field_decreto_firstname')->getValue()) {
      $firstname = $field_firstname[0]['value'];
    }
  }
  if ($user->field_decreto_lastname && !$user->field_decreto_lastname->isEmpty()) {

    if ($field_lastname = $user->get('field_decreto_lastname')->getValue()) {
      $lastname = $field_lastname[0]['value'];
    }
  }
  if ($firstname && $lastname) {
    $name = $firstname . ' ' . $lastname;
  } else {
    $name = $user->getDisplayName();
  }

  $variables['user_name'] = $name;
  $variables['user_initials'] = (new Initials())->name($name)->generate();

  // Initials of title.
  $title = $node->getTitle();
  $variables['label_raw'] = $title;
  $variables['label_initials'] = (new Initials())->name($title)->generate();

  if ($node->getType() == 'decreto_organisation') {
    if ($view_mode == 'full') {
      $variables['help_message'] = \Drupal::service('decreto_help.message')->getMessageMarkup('organisation_view_page');
    }
  }
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node__decreto_meeting(&$variables) {
  $node = $variables['node'];

  if ($variables['view_mode'] === 'table') {
    $decretoMeeting = new DecretoMeeting($node);

    // Note indicator.
    $variables['content']['#contains_notes'] = $decretoMeeting->hasUserNotes();

    // Memos indicator.
    $variables['content']['#contains_memos'] = $decretoMeeting->hasUserMemos();
  }
  elseif ($variables['view_mode'] === 'full') {
    // Access params.
    $variables['content']['#access']['canEdit'] = AccessController::editMeetingAccess($node)->isAllowed();
    $variables['content']['#access']['canDelete'] = $node->access('delete');
    $variables['content']['#access']['decreto_bullet_point']['canCreate'] = AccessController::createBulletPointAccess($node)->isAllowed();
    // We use meeting edit access here, because we don't have any specific
    // bullet point, which can be used in the function
    // AccessController::createBulletPointAttachmentAccess.
    // Doing that we achieve the same result.
    $variables['content']['#access']['decreto_bullet_point_attachment']['canCreate'] = AccessController::editMeetingAccess($node)->isAllowed();
  }
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node__decreto_bullet_point(&$variables) {
  $node = $variables['node'];

  $decretoBP = new DecretoBulletPoint($node);

  // Note indicator.
  $variables['content']['#contains_notes'] = $decretoBP->hasUserNotes();

  // Memos indicator.
  $variables['content']['#contains_memos'] = $decretoBP->hasUserMemos();

  // Access params.
  $variables['content']['#access']['canEdit'] = AccessController::editBulletPointAccess($node)->isAllowed();
  $variables['content']['#access']['canDelete'] = AccessController::deleteBulletPointAccess($node)->isAllowed();
  $variables['content']['#access']['decreto_bullet_point_attachment']['canCreate'] = AccessController::createBulletPointAttachmentAccess($node)->isAllowed();;
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node__decreto_bullet_point_attachment(&$variables) {
  $node = $variables['node'];
  // Note indicator.
  $decretoBPA = new DecretoBulletPointAttachment($node);
  $variables['content']['#contains_notes'] = $decretoBPA->hasUserNotes();

  // Attaching annotator behaviour.
  if ($variables['view_mode'] == 'teaser' || $variables['view_mode'] == 'modal_popup') {
    $variables['#attached']['library'][] = 'decreto_annotator/decreto-annotator';
  }

  // Access params.
  $variables['content']['#access']['canEdit'] = AccessController::editBulletPointAttachmentAccess($node)->isAllowed();
  $variables['content']['#access']['canDelete'] = AccessController::deleteBulletPointAttachmentAccess($node)->isAllowed();
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node__decreto_memo(&$variables) {
  $node = $variables['node'];

  // Path.
  $decretoMemo = new DecretoMemo($node);
  $meetingId = $decretoMemo->getMeeting(FALSE);
  $bulletId = $decretoMemo->getBulletPoint(FALSE);

  if ($meetingId) {
    // Path is formed like : {link-to-meeting}#{bullet_id}.
    $variables['content']['#path'] = (Url::fromRoute('entity.node.canonical', ['node' => $meetingId]))->toString() . '#' . $bulletId;
  }
}

/**
 * Implements template_proprocess_decreto_annotator_note().
 */
function custom_theme_preprocess_decreto_annotator_note(&$variables) {
  $note = $variables['decreto_annotator_note'];

  // Path.
  $meetingId = $note->getMeeting(FALSE);
  $bpaId = $note->getBulletPointAttachment(FALSE);

  if ($meetingId) {
    // Path is formed like : {link-to-meeting}#{bpa_id}.
    $variables['content']['#path'] = (Url::fromRoute('entity.node.canonical', ['node' => $meetingId]))->toString() . '#' . $bpaId;
  }
}

/**
 * Implements template_preprocess_user().
 */
function custom_theme_preprocess_user(&$variables) {
  $user = $variables['user'];
  $view_mode = $variables['elements']['#view_mode'];
  $variables['url'] = $user->toUrl();

  if ($view_mode === 'list') {
    $name = $user->getDisplayName();
    $variables['user_full_name'] = $name;
    $variables['user_initials'] = (new Initials())->name($name)->generate();
  }
}
