<?php

use LasseRafn\Initials\Initials;
use Drupal\decreto_content_modify\Utils\DecretoContentModifyUtils;

/**
 * Implements hook_preprocess_html().
 */
function custom_theme_preprocess_html(array &$variables) {}

/**
 * Implements hook_preprocess_page().
 */
function custom_theme_preprocess_page(array &$variables) {

  // Notification counter.
  $notificationService = \Drupal::service('decreto_notification.notification');
  $notificationCounter = $notificationService->getCounters();
  $variables['counter']['notification'] = $notificationCounter['total'];

  // Note counter.
  $noteService = \Drupal::service('decreto_annotator.note');
  $noteCounter = $noteService->getCounters();
  $variables['counter']['note'] = $noteCounter['total'];

  // Memo counter.
  $contentService = \Drupal::service('decreto_content_modify.content');
  $memoCounter = $contentService->getMemoCounters();
  $variables['counter']['memo'] = $memoCounter['total'];

  // Get initials of user.
  $account = \Drupal::currentUser();
  $user = \Drupal\user\Entity\User::load($account->id());

  $name = '';
  $firstname = '';
  $lastname = '';
  if ($user->field_decreto_firstname && !$user->field_decreto_firstname->isEmpty()) {

    if ($field_firstname = $user->get('field_decreto_firstname')->getValue()) {
      $firstname = $field_firstname[0]['value'];
    }
  }
  if ($user->field_decreto_lastname && !$user->field_decreto_lastname->isEmpty()) {

    if ($field_lastname = $user->get('field_decreto_lastname')->getValue()) {
      $lastname = $field_lastname[0]['value'];
    }
  }
  if ($firstname && $lastname) {
    $name = $firstname . ' ' . $lastname;
  } else {
    $name = $user->getDisplayName();
  }

  $variables['user_name'] = $name;
  $variables['user_initials'] = (new Initials())->name($name)->generate();
}

/*
 * Implements hook_preprocess_paragraph().
 */
function custom_theme_preprocess_paragraph(&$variables) {}


/**
 * Implements template_preprocess_taxonomy_term().
 */
function custom_theme_preprocess_taxonomy_term(&$variables) {
  $term = $variables['term'];
  $view_mode = $variables['view_mode'];

  // Initials of name.
  $name = $term->getName();
  $variables['name_raw'] = $name;
  $variables['name_initials'] = (new Initials())->name($name)->generate();

  // Term bundle specific variables.
  if ($term->bundle() == 'decreto_tax_department') {
    if ($view_mode == 'full') {
      $variables['help_message'] = \Drupal::service('decreto_help.message')->getMessageMarkup('department_view_page');
    }
  }
}

/*
 * Implements hook_theme_suggestions_taxonomy_term_alter().
 */
function custom_theme_theme_suggestions_taxonomy_term_alter(
  &$suggestions,
  $variables,
  $hook
) {
  $suggestions[] = 'taxonomy_term__' . $variables['elements']['#taxonomy_term']->getVocabularyId() . '__' . $variables['elements']['#view_mode'];
  $suggestions[] = 'taxonomy_term__' . $variables['elements']['#view_mode'];
}

/**
 * Implement hook_preprocess_block()
 */
function custom_theme_preprocess_block(&$variables) {
  $id = $variables['elements']['#id'];
  $variables['content']['#attributes']['block'] = $id;

  if ($id === 'custom_theme_decreto_dashboard_counter_coming_meetings') {
    $contentService = \Drupal::service('decreto_content_modify.content');
    $meetingCounter = $contentService->getMeetingCounters();

    $variables['content']['#current_organization'] = $meetingCounter['my_org'];
    $variables['content']['#across_organizations'] = $meetingCounter['total'];

    // Disable caching on block level, as we already cache the counters.
    $variables['#cache']['max-age'] = 0;
  }
  elseif ($id === 'custom_theme_decreto_dashboard_counter_departments') {
    $departmentService = \Drupal::service('decreto_department.department');
    $departmentCounter = $departmentService->getCounters();

    $variables['content']['#current_organization'] = $departmentCounter['my_org'];
    $variables['content']['#across_organizations'] = $departmentCounter['total'];

    // Disable caching on block level, as we already cache the counters.
    $variables['#cache']['max-age'] = 0;
  }
  elseif ($id === 'custom_theme_decreto_dashboard_counter_memos') {
    $contentService = \Drupal::service('decreto_content_modify.content');
    $memoCounter = $contentService->getMemoCounters();

    $variables['content']['#current_organization'] = $memoCounter['my_org'];
    $variables['content']['#across_organizations'] = $memoCounter['total'];

    // Disable caching on block level, as we already cache the counters.
    $variables['#cache']['max-age'] = 0;
  }
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node(&$variables) {
  $node = $variables['node'];
  $user = $node->getOwner();

  // Get initials of user.
  $name = '';
  $firstname = '';
  $lastname = '';
  if ($user->field_decreto_firstname && !$user->field_decreto_firstname->isEmpty()) {

    if ($field_firstname = $user->get('field_decreto_firstname')->getValue()) {
      $firstname = $field_firstname[0]['value'];
    }
  }
  if ($user->field_decreto_lastname && !$user->field_decreto_lastname->isEmpty()) {

    if ($field_lastname = $user->get('field_decreto_lastname')->getValue()) {
      $lastname = $field_lastname[0]['value'];
    }
  }
  if ($firstname && $lastname) {
    $name = $firstname . ' ' . $lastname;
  } else {
    $name = $user->getDisplayName();
  }

  $variables['user_name'] = $name;
  $variables['user_initials'] = (new Initials())->name($name)->generate();

  // Initials of title.
  $title = $node->getTitle();
  $variables['label_raw'] = $title;
  $variables['label_initials'] = (new Initials())->name($title)->generate();
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node__decreto_meeting(&$variables) {
  $node = $variables['node'];

  if ($variables['view_mode'] === 'table') {

    // Note indicator.
    $noteService = \Drupal::service('decreto_annotator.note');
    $variables['content']['#contains_notes'] = $noteService->getMeetingHasNote($node);

    // Memos indicator.
    $decretoContentService = \Drupal::service('decreto_content_modify.content');
    $variables['content']['#contains_memos'] = $decretoContentService->getMeetingHasMemo($node);
  }
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node__decreto_bullet_point(&$variables) {
  $node = $variables['node'];
  // Note indicator.
  $noteService = \Drupal::service('decreto_annotator.note');
  $variables['content']['#contains_notes'] = $noteService->getBulletPointHasNote($node);
}

/**
 * Implements template_proprocess_node().
 */
function custom_theme_preprocess_node__decreto_bullet_point_attachment(&$variables) {
  $node = $variables['node'];
  // Note indicator.
  $noteService = \Drupal::service('decreto_annotator.note');
  $variables['content']['#contains_notes'] = $noteService->getBulletPointAttachmentHasNote($node);
  $variables['content']['bullet_point_id'] = DecretoContentModifyUtils::getRelatedNodes($node, 'decreto_bullet_point', FALSE);
}

/**
 * Implements template_preprocess_user().
 */
function custom_theme_preprocess_user(&$variables) {
  $user = $variables['user'];
  $view_mode = $variables['elements']['#view_mode'];
  $variables['url'] = $user->toUrl();

  if ($view_mode === 'list') {
    $name = '';
    $firstname = '';
    $lastname = '';
    if ($user->field_decreto_firstname && !$user->field_decreto_firstname->isEmpty()) {

      if ($field_firstname = $user->get('field_decreto_firstname')->getValue()) {
        $firstname = $field_firstname[0]['value'];
      }
    }
    if ($user->field_decreto_lastname && !$user->field_decreto_lastname->isEmpty()) {

      if ($field_lastname = $user->get('field_decreto_lastname')->getValue()) {
        $lastname = $field_lastname[0]['value'];
      }
    }
    if ($firstname && $lastname) {
      $name = $firstname . ' ' . $lastname;
    } else {
      $name = $user->getDisplayName();
    }

    $variables['user_full_name'] = $name;
    $variables['user_initials'] = (new Initials())->name($name)->generate();
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function custom_theme_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  // That is needed in order to make form  opened via popup to see the template.
  $suggestions[] = 'form__' . str_replace('-','_',$variables['element']['#form_id']);
}
