<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\message\Entity\Message;

/**
 * @file
 * Decreto notification module file.
 */

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @see decreto_notification_meeting_notify().
 */
function decreto_notification_node_insert(EntityInterface $node) {
  if ($node->bundle() == 'decreto_meeting') {
    decreto_notification_meeting_notify($node);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * @see decreto_notification_meeting_notify().
 */
function decreto_notification_node_update(EntityInterface $node) {
  if ($node->bundle() == 'decreto_meeting') {
    decreto_notification_meeting_notify($node);
  }
}

/**
 * Creates and sends notification when meeting is created or updated.
 *
 * @param EntityInterface $node
 *   Meeting node.
 */
function decreto_notification_meeting_notify(EntityInterface $node) {
  // Creating message.
  $message = Message::create([
    'template' => 'decreto_meeting_modify',
    'uid' => $node->get('uid'),
  ]);
  $message->set('field_decreto_notif_meeting', $node);
  $message->save();

  // Finding subscribers.
  if ($field_decreto_meet_department = $node->field_decreto_meet_department->first()) {
    $department = $field_decreto_meet_department->entity;
    $subscribers = \Drupal::service('message_subscribe.subscribers');

    if ($department) {
      // Notifying subscribers.
      $subscribers->sendMessage($department, $message);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Subscribes or unsubscribes user to the department events based on user
 * departments list.
 */
function decreto_notification_user_presave(EntityInterface $user) {
  // Only subscribing the existing users.
  if ($user->isNew()) {
    return;
  }

  $flag_service = \Drupal::service('flag');
  $flag = $flag_service->getFlagById('subscribe_decreto_tax_department');

  // Getting user departments, ids.
  $userDepartments = array_column($user->field_decreto_usr_departments->getValue(), 'target_id');

  // Getting all departments, loaded.
  $vid = 'decreto_tax_department';
  $allDeparments = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid, 0, NULL, TRUE);

  foreach ($allDeparments as $department) {
    if (in_array($department->id(), $userDepartments)) {
      // Ensure flagging is present, if not = subscribe user.
      $flagging = $flag_service->getEntityFlaggings($flag, $department, $user);

      if (empty($flagging)) {
        $flag_service->flag($flag, $department, $user);
      }
    }
    else {
      // Ensure flagging is not present, if present = unsubscribe user.
      $flagging = $flag_service->getEntityFlaggings($flag, $department, $user);

      if (!empty($flagging)) {
        $flag_service->unflag($flag, $department, $user);
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * When message is deleted, function also deletes all related
 * decreto_notification entities.
 */
function decreto_notification_message_delete(EntityInterface $message) {
  $query = \Drupal::entityQuery('decreto_notification')
    ->condition('mid', $message->id());
  $notification_ids = $query->execute();

  $storage_handler = \Drupal::entityTypeManager()->getStorage('decreto_notification');
  $notifications = $storage_handler->loadMultiple($notification_ids);

  // Deleting each notification individually so that Notification->delete()
  // function is executed.
  foreach ($notifications as $notification) {
    $notification->delete();
  }
}

/**
 * Implements hook_theme().
 */
function decreto_notification_theme() {
  return [
    'decreto_notification' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for decreto_notification templates.
 *
 * Default template: decreto-notification.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - decreto_notification: The decreto_notification object.
 *   - view_mode: View mode; e.g., 'full', 'teaser', etc.
 */
function template_preprocess_decreto_notification(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];

  $variables['decreto_notification'] = $variables['elements']['#decreto_notification'];

  $created_ts = $variables['decreto_notification']->created->value;

  // Was it created today?
  if (time() - $created_ts < 24*60*60) {
    $variables['date'] = \Drupal::service('date.formatter')->format($created_ts, 'html_time', '');
  }
  else {
    $variables['date'] = \Drupal::service('date.formatter')->format($created_ts, 'html_date', '');
  }
  unset($variables['elements']['created']);

  if ($department = $variables['decreto_notification']->getDepartment()) {
    $variables['department'] = $department->label();
  }

  // Helpful $content variable for templates.
  $variables += ['content' => [
    '#unread' => $variables['decreto_notification']->unread->value,
  ]];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Notification resolve path.
  $variables['url'] = $variables['decreto_notification']->toUrl()->toString();
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function decreto_notification_theme_suggestions_decreto_notification(array $variables) {
  $suggestions = [];

  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'decreto_notification__' . $sanitized_view_mode;

  return $suggestions;
}
