<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\decreto_content_modify\Utils\DecretoContentModifyUtils;
use Drupal\search_api\Plugin\search_api\datasource\ContentEntity;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\user\Entity\User;

/**
 * Implements hook_entity_update().
 *
 * IF decreto_bullet_point or decreto_bullet_point_attachment is updated, finds
 * a corresponding meeting and marks it as updated.
 *
 * @see decreto_search_mark_entity_updated().
 */
function decreto_search_node_update(EntityInterface $entity) {
  if ($entity->getType() == 'decreto_bullet_point' || $entity->getType() == 'decreto_bullet_point_attachment') {
    $meeting = DecretoContentModifyUtils::getRelatedNodes($entity, 'decreto_meeting', TRUE);
    if (!empty($meeting)) {
      decreto_search_mark_entity_updated($meeting);
    }
  }
}

/**
 * Implements hook_entity_delete().
 *
 * IF decreto_bullet_point or decreto_bullet_point_attachment is deleted, finds
 * a corresponding meeting and marks it as updated.
 *
 * @see decreto_search_mark_entity_updated().
 */
function decreto_search_node_delete(EntityInterface $entity) {
  if ($entity->getType() == 'decreto_bullet_point' || $entity->getType() == 'decreto_bullet_point_attachment') {
    $meeting = DecretoContentModifyUtils::getRelatedNodes($entity, 'decreto_meeting', TRUE);
    if (!empty($meeting)) {
      decreto_search_mark_entity_updated($meeting);
    }
  }
}

/**
 * Updates the corresponding tracking table entries for each index that tracks
 * this entity.
 *
 * @see search_api_entity_update().
 */
function decreto_search_mark_entity_updated(EntityInterface $entity) {
  $entity_id = $entity->id();

  $indexes = ContentEntity::getIndexesForEntity($entity);
  if (!$indexes) {
    return;
  }

  $datasource_id = 'entity:' . $entity->getEntityTypeId();
  $combine_id = function ($langcode) use ($entity_id) {
    return $entity_id . ':' . $langcode;
  };
  $updated_item_ids = $entity->getTranslationLanguages();
  $updated_item_ids = array_map($combine_id, array_keys($updated_item_ids));
  foreach ($indexes as $index) {
    if ($updated_item_ids) {
      $index->trackItemsUpdated($datasource_id, $updated_item_ids);
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function decreto_search_theme_suggestions_form(array $variables) {
  // TODO: consider moving to theme.
  if (!empty($variables['element']['#id'])) {
    $suggestions[] = 'form__' . str_replace('-', '_', $variables['element']['#id']);
  }

  return $suggestions;
}

/**
 * Implements hook_form_alter()
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function decreto_search_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-decreto-search-meetings-decreto-page-meetings-search') {
    // Adding help message.
    $form[] = \Drupal::service('decreto_help.message')->getMessageMarkup('meetings_search_form');

    // Limit departments checkbox.
    $form['ld'] = [
      '#type' => 'checkbox',
      '#title' => t('Show only meetings from departments I am member of'),
    ];

    // Changing type of date fields.
    $form['from']['#type'] = 'date';
    $form['to']['#type'] = 'date';
  }
}

/**
 * Implements hook_views_query_alter().
 *
 * Toggles showing meeting from only user's departments and all departments.
 */
function decreto_search_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'decreto_search_meetings') {
    $limitDepartments = \Drupal::request()->query->get('ld');

    if ($limitDepartments) {
      $user = User::load(\Drupal::currentUser()->id());
      $userDepartments = array_column($user->field_decreto_usr_departments->getValue(), 'target_id');

      $query->addWhere('', 'department_tid', $userDepartments, 'IN');
    }

    // Attempting to find field_decreto_meet_end_date timestamp from 00:00:00
    // to 23:59:59, if present.
    foreach ($query->getWhere() as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        // Is filter present?
        if ($condition[0] == 'field_decreto_meet_end_date') {
          // Getting value.
          $end_date_timestamp = $condition[1];

          // Changing time to 23:59:59.
          $end_date_timestamp_end_of_day   = strtotime("tomorrow", $end_date_timestamp) - 1;

          // Swapping value.
          $condition[1] = $end_date_timestamp_end_of_day;
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_node().
 *
 * If decreto_meeting is displayed on meetings search page, the search param is
 * added to the url.
 */
function decreto_search_preprocess_node(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();

  if ($current_path == '/meetings') {
    $node = $variables['elements']['#node'];
    if ($node->getType() != 'decreto_meeting') {
      return;
    }

    $search_param = \Drupal::request()->query->get('s');
    $node = $variables['elements']['#node'];
    $variables['url'] = $node
      ->url('canonical', array(
        'language' => $node
            ->language(),
        'query' => [
          's' => $search_param
        ],

      ));

    // We don't want to cache that, since search param is dynamic.
    $variables['#cache']['max-age'] = 0;
  }
}

/**
 * Implements hook_decreto_help_messages().
 */
function decreto_search_decreto_help_messages() {
  return [
    'meetings_search_form' => 'Meetings search (form)',
    'meetings_search_table' => 'Meetings search (results table)'
  ];
}
