<?php
module_load_include('inc', 'decreto_context_menu', '/inc/decreto_context_menu.utils');

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function decreto_context_menu_preprocess_node(&$variables) {
  $node = $variables['node'];
  $variables['decreto_context_menu'] = decreto_context_menu_get_menu($node, $variables['view_mode']);
}

/**
 * Function that returns themed context menu based on view_mode
 * @param $node
 * @param $view_mode
 * @return array
 */
function decreto_context_menu_get_menu($node, $view_mode) {
  return array(
    '#theme' => 'decreto_context_menu',
    '#links' => decreto_context_menu_get_menu_links($node, $view_mode),
  );
}

/**
 * Implements hook_theme().
 */
function decreto_context_menu_theme(&$vars) {
  return array(
    'decreto_context_menu' => array(
      'variables' => array(
        'links' => NULL
      )
    )
  );
}