<?php
/*
 * Return FALSE if there is at least one meeting in any of the user committees
 * Used for adding indicator  in Calendar view
 */
function decreto_helper_calendar_view_fields_filter_by_user_committees($meeting_id){
  $user_committes = decreto_helper_get_user_committees();
  $meeting =  \Drupal\node\Entity\Node::load($meeting_id->__toString());
  $meeting_committee=$meeting->get('field_decreto_meet_committee')->getValue();
  if (!in_array($meeting_committee[0]['target_id'], $user_committes)) return TRUE;

  return FALSE;
}

/*
 * Return current user committtees
 */
function decreto_helper_get_user_committees(){
  // Load the current user.
  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  $user_committees = $user->get('field_decreto_usr_coms')->getValue();
  if (isset($user_committees)){
    foreach ($user_committees as $com){
     $terms[] = $com['target_id'];
           
    }
  }
  return $terms;
  
}