<?php

/**
 * Implements hook_theme().
 */
//function decreto_content_modify_theme(&$vars) {
//  //kint($vars);
//  //$vars['test'] = 'testik1';
//    drupal_set_message(print_r($vars,1));
//
//  //kint($vars);
//    'decreto_content_modify_bullet_point' => array(
//      'variables' => array(
//        'node' => NULL,
//        'expanded' => false,
//        'content' => NULL,
//        'label' => NULL,
//        'decreto_context_menu' => NULL,
//        'add_bpa' => NULL
//      ),
//    )
//  );
//}
