<?php

use Drupal\decreto_content_modify\Utils\DecretoContentModifyUtils as DecretoContentUtils;

/**
 * Implements hook_theme().
 */
//function decreto_content_modify_theme(&$vars) {
//  //kint($vars);
//  //$vars['test'] = 'testik1';
//    drupal_set_message(print_r($vars,1));
//
//  //kint($vars);
//    'decreto_content_modify_bullet_point' => array(
//      'variables' => array(
//        'node' => NULL,
//        'expanded' => false,
//        'content' => NULL,
//        'label' => NULL,
//        'decreto_context_menu' => NULL,
//        'add_bpa' => NULL
//      ),
//    )
//  );
//}

/**
 * Implements hook_preprocess_node().
 */
function decreto_content_modify_preprocess_node(&$variables) {
  $uid = \Drupal::currentUser()->id();

  if ($variables['node']->getType() == 'decreto_bullet_point') {
    $query = \Drupal::entityQuery('node')
      ->condition('status', 1)
      ->condition('type', 'decreto_speaker_paper')
      ->condition('uid', $uid)
      ->condition('field_decreto_sp_bp', $variables['node']->id());
    $nids = $query->execute();
    foreach ($nids as $key => $value) {
      $node = \Drupal\node\Entity\Node::load($value);
      $variables['speaker_papers'][] = node_view($node);
    }
  }
}

/**
 * Implements hook_system_breadcrumb_alter()
 * @param $breadcrumb
 * @param $route_match
 * @param array $context
 */
function decreto_content_modify_system_breadcrumb_alter(&$breadcrumb, $route_match, array $context) {
  foreach ($breadcrumb->getLinks() as $exisiting_link) {
    if ($exisiting_link->getUrl()->getRouteName() == '<front>') {
      $exisiting_link->setText(t('Dashboard'));
    }
  }

  if ($node = $route_match->getParameter('node')) {
    if ($node->getType() == 'decreto_meeting' || $node->getType() == 'decreto_bullet_point' || $node->getType() == 'decreto_bullet_point_attachment') {
      $breadcrumb->addLink(\Drupal\Core\Link::createFromRoute(t('Meetings'), 'view.decreto_search.page')); //TODO: change to meetings
    }

    if ($node->getType() == 'decreto_bullet_point' || $node->getType() == 'decreto_bullet_point_attachment') {
      $meeting = DecretoContentUtils::getRelatedNodes($node, 'decreto_meeting');
      $breadcrumb->addLink($meeting->toLink());
    }

    if ($node->getType() == 'decreto_bullet_point_attachment') {
      $bp = DecretoContentUtils::getRelatedNodes($node, 'decreto_bullet_point');
      $breadcrumb->addLink($bp->toLink());
    }
  }
}