<?php

/**
 * Implements hook_theme().
 */
//function decreto_content_modify_theme(&$vars) {
//  //kint($vars);
//  //$vars['test'] = 'testik1';
//    drupal_set_message(print_r($vars,1));
//
//  //kint($vars);
//    'decreto_content_modify_bullet_point' => array(
//      'variables' => array(
//        'node' => NULL,
//        'expanded' => false,
//        'content' => NULL,
//        'label' => NULL,
//        'decreto_context_menu' => NULL,
//        'add_bpa' => NULL
//      ),
//    )
//  );
//}

/**
 * Implements hook_preprocess_node().
 */
function decreto_content_modify_preprocess_node(&$variables) {
  $uid = \Drupal::currentUser()->id();

 if($variables['node']->getType()=='decreto_bullet_point') {
   $query = \Drupal::entityQuery('node')
          ->condition('status', 1)
          ->condition('type', 'decreto_speaker_paper')
          ->condition('uid', $uid)
          ->condition('field_decreto_sp_bp', $variables['node']->id());
   $nids =  $query->execute();
   foreach ($nids as $key => $value){
   $node = \Drupal\node\Entity\Node::load($value);
   $variables['speaker_papers'][]=node_view($node);
   }
 }
}