<?php 

function  decreto_bpa_files_conversion_manager_schema() {
  $schema['decreto_bpa_files_conversion_manager_pdf_files'] = array(
    'description' => 'This table is used for save file info  for * -> PDF convertion',
    'fields' => array(
      'fid' => array(
        'description' => 'The file entry fid.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'defualt' => 0,
      ),
      'filename' => array(
        'description' => 'Name of the file',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
      'tmp_filename' => array(
        'description' => 'Temporary filename',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
      'status' => array(
        'description' => 'Status of the convertion',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
      'message' => array(
        'description' => 'Error message',
        'type' => 'text',
        'serialize' => TRUE,
      ), 
      'attempt' => array(
        'description' => 'The number of attempts file has been tried to be convered',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'defualt' => 0,
      ),
    ),
    'primary key' => array('fid'),
  );
  return $schema;
}
