<?php

/**
 * @file
 * Contains decreto_departmnet.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\decreto_department\Controller\AccessController;
use Drupal\decreto_department\Entity\DecretoDepartment;
use Drupal\decreto_department\Services\DepartmentService;
use Drupal\decreto_user\Entity\DecretoUser;
use Drupal\taxonomy\TermInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function decreto_department_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the decreto_department module.
    case 'help.page.decreto_department':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Decreto departments functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_decreto_help_messages().
 */
function decreto_department_decreto_help_messages() {
  return [
    'department_create_edit_form' => 'Department create/edit form',
    'department_view_page' => 'Department view page',
    'department_meetings_list' => 'Coming meetings in this department (block)',
    'department_members_list' => 'Members of this department (block)',
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Invalidates caches related decreto_tax_department.
 */
function decreto_department_taxonomy_term_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'decreto_tax_department') {
    // Invalidating meetings count.
    Cache::invalidateTags([DepartmentService::CACHE_ID_DECRETO_DEPARTMENT_COUNTERS]);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Invalidates caches related decreto_tax_department.
 * Removes this department from all users.
 */
function decreto_department_taxonomy_term_delete(EntityInterface $entity) {
  if ($entity->bundle() == 'decreto_tax_department') {
    // Invalidating departments count.
    Cache::invalidateTags([DepartmentService::CACHE_ID_DECRETO_DEPARTMENT_COUNTERS]);

    $decretoDepartment = new DecretoDepartment($entity);

    // Remove department from all users.
    $departmentUsers = $decretoDepartment->getUsers();
    foreach ($departmentUsers as $user) {
      $decretoUser = new DecretoUser($user);
      $decretoUser->removeDepartment($entity->id());
    }

    // Deleting dependent meetings.
    $departmentMeetings = $decretoDepartment->getMeetings();
    foreach ($departmentMeetings as $meeting) {
      $meeting->delete();
    }
  }
}

/**
 * Implements hook_theme().
 */
function decreto_department_theme() {
  return [
    'decreto_department_departments_view_context_links' => [
      'variables' => [
        'create_department' => NULL,
        'create_department_use_ajax' => NULL,
        'edit_department' => NULL,
        'department_user_create' => NULL,
        'department_id' => NULL,
        'access' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function decreto_department_views_data() {
  $data['views']['decreto_department_departments_view_context_links'] = [
    'title' => t('Decreto departments view links'),
    'help' => t('Renders "Create" link to be used in department views.'),
    'area' => [
      'id' => 'decreto_department_departments_view_context_links',
    ],
  ];

  return $data;
}

/**
 * Implements hook_taxonomy_term_access().
 */
function decreto_department_taxonomy_term_access(TermInterface $term, $op, AccountInterface $account) {
  if ($op == 'update') {
    if ($term->bundle() == 'decreto_tax_department') {
      return AccessController::editDepartmentAccess($term, $account);
    }
  }
  elseif ($op == 'delete') {
    if ($term->bundle() == 'decreto_tax_department') {
      return AccessController::deleteDepartmentAccess($term, $account);
    }
  }

  return AccessResult::neutral();
}
