<?php

/**
 * @file
 * Contains decreto_organisation.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\decreto_user\Entity\DecretoUser;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\user\Entity\User;

/**
 * Implements hook_views_query_alter().
 *
 * Adds the organisation filter to the presented content.
 */
function decreto_organisation_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  switch ($view->id()) {
    case 'decreto_meetings':
    case 'decreto_user_departments':
    case 'decreto_calender':
    case 'decreto_departments':
    case 'decreto_memos':
    case 'decreto_notes':
    case 'decreto_notifications':
      switch ($view->current_display) {
        case 'decreto_block_my_meetings':
        case 'decreto_block_all_meetings':
        case 'decreto_page_my_departments':
        case 'decreto_block_my_departments':
        case 'calendar_block':
        case 'decreto_page_meetings':
        case 'decreto_page_departments':
        case 'decreto_page_memos':
        case 'decreto_memo_popup_embed':
        case 'decreto_note_popup_embed':
        case 'decreto_note_page':
        case 'decreto_notification_popup_embed':
        case 'decreto_notification_page':
          $org_id = \Drupal::service('decreto_organisation.organisation')->getSelectedOrganisation(FALSE);
          if ($org_id) {
            $query->addWhere('1', 'node_field_data_taxonomy_term__field_decreto_dep_org.nid', $org_id, '=');
          }

          break;

        case 'decreto_page_other_organisations_meetings':
        case 'decreto_page_other_organisations_departments':
        case 'decreto_page_other_organisations_memos':
          $org_id = \Drupal::service('decreto_organisation.organisation')->getSelectedOrganisation(FALSE);
          if ($org_id) {
            $query->addWhere('1', 'node_field_data_taxonomy_term__field_decreto_dep_org.nid', $org_id, '!=');
          }

          break;

      }
    case 'user_search':
      if ($view->current_display == 'users_list') {
        $org_id = \Drupal::service('decreto_organisation.organisation')->getSelectedOrganisation(FALSE);
        if ($org_id) {
          $query->addWhere('1', 'node_field_data_user__field_decreto_usr_orgs.nid', $org_id, '=');
        }
      }
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Removes this organisation from all users.
 */
function decreto_organisation_node_delete(EntityInterface $entity) {
  if ($entity->getType() == 'decreto_organisation') {

    // Remove department from all users.
    $query = \Drupal::entityQuery('user')
      ->condition('status', 1)
      ->condition('field_decreto_usr_orgs', $entity->id(), 'IN');
    $users_ids = $query->execute();
    if (!empty($users_ids)) {
      foreach ($users_ids as $user_id) {
        $user = User::load($user_id);
        $decretoUser = new DecretoUser($user);
        $decretoUser->removeOrganisation($entity->id());
      }
    }

    //TODO: Think if this organisation needs to be removed from department and
    // location terms.
  }
}

/**
 * Implements hook_decreto_help_messages().
 */
function decreto_organisation_decreto_help_messages() {
  return [
    'organisation_create_edit_form' => 'Department create/edit form',
    'organisation_view_page' => 'Organisation view page',
    'organisation_members_list' => 'Members of this organisation (block)',
  ];
}

/**
 * Implements hook_theme().
 */
function decreto_organisation_theme() {
  return [
    'decreto_organisation_organisations_view_context_links' => [
      'variables' => [
        'create_organisation' => NULL,
        'edit_organisation' => NULL,
        'organisation_id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function decreto_organisation_views_data() {
  $data['views']['decreto_organisation_organisations_view_context_links'] = [
    'title' => t('Decreto organisation view links'),
    'help' => t('Renders "Create", "Edit" link to be used in organisation views.'),
    'area' => [
      'id' => 'decreto_organisation_organisations_view_context_links',
    ],
  ];

  return $data;
}


