<?php

/**
 * @file
 * Contains decreto_organisation.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\decreto_organisation\Entity\DecretoOrganisation;
use Drupal\decreto_user\Entity\DecretoUser;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\user\Entity\User;

/**
 * Implements hook_views_query_alter().
 *
 * Adds the organisation filter to the presented content.
 */
function decreto_organisation_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  switch ($view->id()) {
    case 'decreto_meetings':
    case 'decreto_user_departments':
    case 'decreto_calender':
    case 'decreto_departments':
    case 'decreto_memos':
    case 'decreto_notes':
      switch ($view->current_display) {
        case 'decreto_block_my_meetings':
        case 'decreto_block_all_meetings':
        case 'decreto_page_my_departments':
        case 'decreto_block_my_departments':
        case 'calendar_block':
        case 'decreto_page_meetings':
        case 'decreto_page_organisation_departments':
        case 'decreto_page_memos':
        case 'decreto_memo_popup_embed':
        case 'decreto_note_popup_embed':
        case 'decreto_note_page':
        case 'decreto_notification_popup_embed':
        case 'decreto_notification_page':
          $org_id = \Drupal::service('decreto_organisation.organisation')->getSelectedOrganisation(FALSE);
          if ($org_id) {
            $query->addWhere('1', 'node_field_data_taxonomy_term__field_decreto_dep_org.nid', $org_id, '=');
          }

          break;

        case 'decreto_page_other_organisations_meetings':
        case 'decreto_page_other_organisations_departments':
        case 'decreto_page_other_organisations_memos':
          $org_id = \Drupal::service('decreto_organisation.organisation')->getSelectedOrganisation(FALSE);
          if ($org_id) {
            $query->addWhere('1', 'node_field_data_taxonomy_term__field_decreto_dep_org.nid', $org_id, '!=');
          }

          break;

      }

      break;

    case 'decreto_users':
      if ($view->current_display == 'decreto_page_organisation_users') {
        $org_id = \Drupal::service('decreto_organisation.organisation')->getSelectedOrganisation(FALSE);
        if ($org_id) {
          $query->addWhere('1', 'node_field_data_user__field_decreto_usr_orgs.nid', $org_id, '=');
        }
      }

      break;

    case 'decreto_notifications':
      $org_id = \Drupal::service('decreto_organisation.organisation')->getSelectedOrganisation(FALSE);
      if ($org_id) {
        $query->addWhere('1', 'decreto_notification_notifications.org_id', $org_id, '=');
      }

      break;

  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Removes this organisation from all users.
 */
function decreto_organisation_node_delete(EntityInterface $entity) {
  if ($entity->getType() == 'decreto_organisation') {

    $decretoOrganisation = new DecretoOrganisation($entity);

    // Remove organisation from all users.
    $users = $decretoOrganisation->getUsers();
    foreach ($users as $user) {
      $decretoUser = new DecretoUser($user);
      $decretoUser->removeOrganisation($entity->id());
    }

    // Remove dependent departments.
    $departments = $decretoOrganisation->getDepartments();
    foreach ($departments as $department) {
      $department->delete();
    }

    // Remove dependent locations.
    $locations = $decretoOrganisation->getLocations();
    foreach ($locations as $location) {
      $location->delete();
    }
  }
}

/**
 * Implements hook_decreto_help_messages().
 */
function decreto_organisation_decreto_help_messages() {
  return [
    'organisation_create_edit_form' => 'Department create/edit form',
    'organisation_view_page' => 'Organisation view page',
    'organisation_members_list' => 'Members of this organisation (block)',
  ];
}

/**
 * Implements hook_theme().
 */
function decreto_organisation_theme() {
  return [
    'decreto_organisation_organisations_view_context_links' => [
      'variables' => [
        'create_organisation' => NULL,
        'create_organisation_use_ajax' => NULL,
        'edit_organisation' => NULL,
        'organisation_id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function decreto_organisation_views_data() {
  $data['views']['decreto_organisation_organisations_view_context_links'] = [
    'title' => t('Decreto organisation view links'),
    'help' => t('Renders "Create", "Edit" link to be used in organisation views.'),
    'area' => [
      'id' => 'decreto_organisation_organisations_view_context_links',
    ],
  ];

  return $data;
}
