<?php

/**
 * Implements hook_schema()
 *
 * @return mixed
 */
function decreto_pdf2htmlex_schema() {
  $schema['decreto_pdf2htmlex_files'] = array(
    'description' => 'This table is used as schedule for PDF -> HTML convertion',
    'fields' => array(
      'fid' => array(
        'description' => 'The file entry fid.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'defualt' => 0,
      ),
      'did' => array(
        'description' => 'The destination nid.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'filename' => array(
        'description' => 'Name of the file',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
      'created_filepath' => array(
        'description' => 'The path of the created HTML output',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
      'status' => array(
        'description' => 'The information about the job',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
    ),
    'primary key' => array('fid', 'did'),
  );
  return $schema;
}