<?php

use Drupal\decreto_pdf2htmlex\Plugin\Field\FieldFormatter\FieldFormatterUtility;
use Drupal\file\Entity\File;

/**
 * Implements hook_theme().
 */
function decreto_pdf2htmlex_theme() {
  return array(
    'decreto_pdf2htmlex_rendered_html_formatter' => array(
      'variables' => array('file' => NULL),
    ),
    'decreto_pdf2htmlex_rendered_html_first_page_formatter' => array(
      'variables' => array('file' => NULL),
    ),
  );
}

/**
 * Implements template_preprocess_decreto_pdf2htmlex_rendered_html_formatter().
 */
function template_preprocess_decreto_pdf2htmlex_rendered_html_formatter(&$vars) {
  template_preprocess_file_link($vars);
  $vars['html'] = FieldFormatterUtility::getAllPages($vars['file']);
}

/**
 * Implements template_preprocess_decreto_pdf2htmlex_rendered_html_first_page_formatter().
 */
function template_preprocess_decreto_pdf2htmlex_rendered_html_first_page_formatter(&$vars) {
  template_preprocess_file_link($vars);
  $vars['html'] = FieldFormatterUtility::getFirstPage($vars['file']);
}

/**
 * Implements hook_cron().
 */
function decreto_pdf2htmlex_cron() {
  $queue_factory = \Drupal::service('queue');
  $queue = $queue_factory->get('decreto_pdf2htmlex_queue');

  $scheduled_files = \Drupal::service('decreto_pdf2htmlex.pdf2htmlex')->getScheduledFiles();

  foreach ($scheduled_files as $schedule_file) {
    $queue->createItem($schedule_file);
  }
}

/**
 * Implements hook_entity_delete().
 */
function decreto_pdf2htmlex_file_delete(File $file) {
  if (\Drupal::service('decreto_pdf2htmlex.pdf2htmlex')->isFileScheduled($file->id())) {
    \Drupal::service('decreto_pdf2htmlex.pdf2htmlex')->deleteScheduledFile($file->id());
  }
}
