<?php

function  decreto_pdf_conversion_manager_schema() {
  $schema['decreto_pdf_conversion_manager_files'] = array(
    'description' => 'This table is used for save file info  for * -> PDF convertion',
    'fields' => array(
      'fid' => array(
        'description' => 'The file entry fid.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'did' => array(
        'description' => 'The destination nid.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'filename' => array(
        'description' => 'Name of the file',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
      'created_filepath' => array(
        'description' => 'The path of the created output',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
      'status' => array(
        'description' => 'Status of the conversion',
        'type' => 'varchar',
        'length' => 1024,
        'serialize' => TRUE,
      ),
      'message' => array(
        'description' => 'Error message',
        'type' => 'text',
        'serialize' => TRUE,
      ),
      'attempt' => array(
        'description' => 'The number of attempts file has been tried to be converted',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'convert_to_html' => array(
        'description' => 'File must be scheduled for HTML conversion',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('fid'),
  );
  return $schema;
}

/**
 * Implements hook_requirements().
 */
function decreto_pdf_conversion_manager_requirements($phase) {
  $requirements = array();
  $passed_requirements = array();

  // Checking unoconv.
  $unoconv_version = \Drupal::service('decreto_pdf_conversion_manager.pdfConversionManagerService')->getVersion('unoconv');
  if (!$unoconv_version) {
    if ($phase == 'runtime') {
      $requirements['decreto_pdf_conversion_manager_unoconv'] = array(
        'title' => t('Decreto PDF converter manager'),
        'value' => 'unoconv cannot be found, install it with `sudo apt install unoconv`',
        'severity' => REQUIREMENT_ERROR,
      );
    }
  }
  else {
    $passed_requirements['unoconv'] = 'unoconv: ' . $unoconv_version;
  }

  // Checking ImageMagick: convert.
  $image_magick_version = \Drupal::service('decreto_pdf_conversion_manager.pdfConversionManagerService')->getVersion('imagemagick');
  if (!$image_magick_version) {
    if ($phase == 'runtime') {
      $requirements['decreto_pdf_conversion_manager_imagemagick'] = array(
        'title' => t('Decreto PDF converter manager'),
        'value' => 'imagemagick cannot be found, install it with `sudo apt install imagemagick`',
        'severity' => REQUIREMENT_ERROR,
      );
    }
  }
  else {
    $passed_requirements['imagemagick'] = 'imagemagick: ' . $image_magick_version;
  }

  // Checking iconv.
  $iconv_version = \Drupal::service('decreto_pdf_conversion_manager.pdfConversionManagerService')->getVersion('iconv');
  if (!$iconv_version) {
    if ($phase == 'runtime') {
      $requirements['decreto_pdf_conversion_manager_iconv'] = array(
        'title' => t('Decreto PDF converter manager'),
        'value' => 'iconv cannot be found, install it with `sudo apt-get install libc6`',
        'severity' => REQUIREMENT_ERROR,
      );
    }
  }
  else {
    $passed_requirements['iconv'] = 'iconv: ' . $iconv_version;
  }

  // Listing requirements that passed.
  if (!empty($passed_requirements)) {
    if ($phase == 'runtime') {
      $requirements['decreto_pdf_conversion_manager'] = array(
        'title' => t('Decreto PDF converter manager'),
        'value' => 'Successfully installed: ' . implode($passed_requirements, '; '),
        'severity' => REQUIREMENT_OK,
      );
    }

  }

  return $requirements;
}
