<?php

use Drupal\file\Entity\File;

/**
 * Implements hook_cron()
 */
function decreto_pdf_conversion_manager_cron() {
  $queue_factory = \Drupal::service('queue');
  $queue = $queue_factory->get('decreto_pdf_conversion_manager_queue');

  $scheduled_files = \Drupal::service('decreto_pdf_conversion_manager.pdfConversionManagerService')->getScheduledFiles();

  foreach ($scheduled_files as $schedule_file) {
    $queue->createItem($schedule_file);
  }
}

/**
 * Implements hook_entity_delete().
 */
function decreto_pdf_conversion_manager_file_delete(File $file) {
  if (\Drupal::service('decreto_pdf_conversion_manager.pdfConversionManagerService')->isFileScheduled($file->id())) {
    \Drupal::service('decreto_pdf_conversion_manager.pdfConversionManagerService')->deleteScheduledFile($file->id());
  }
}
